on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      os:
        required: true
        type: string
      deps_cmdline:
        required: true
        type: string
      extra_options:
        required: true
        type: string
      build_type:
        required: true
        type: string
    secrets:
      MACOS_CERTIFICATE:
        required: false
      MACOS_CERTIFICATE_PASSWORD:
        required: false
      MACOS_CERTIFICATE_ID:
        required: false

jobs:
  run_build:
    name: ${{ inputs.name }} ${{ inputs.build_type }}
    runs-on: ${{ inputs.os }}
    steps:
    - name: Setup
      uses: actions/checkout@v4

    - name: Setup
      id: ghd
      uses: proudust/gh-describe@v2

    - name: Setup
      uses: ilammy/msvc-dev-cmd@v1

    - name: Dependencies
      shell: bash
      run: |
        if [[ -n "${{ inputs.deps_cmdline }}" ]]; then
          eval ${{ inputs.deps_cmdline }}
        fi

    - name: Configure
      shell: bash
      run: |
        mkdir build
        cmake -B build -S . \
          -DCMAKE_BUILD_TYPE=${{ inputs.build_type }} \
          -DPK3_QUIET_ZIPDIR=ON \
          ${{ inputs.extra_options }} \
          -G Ninja

    - name: Build
      shell: bash
      run: |
        export GIT_DESCRIBE="${{ steps.ghd.outputs.describe }}"
        export MAKEFLAGS=--keep-going
        cmake --build build --config ${{ inputs.build_type }}

    - name: Package
      shell: bash
      run: |
        function fetch() { { curl -L "$3" | tee "$1" | sha256sum ; } && { echo "$2 $1" | sha256sum -c - ; } ; }

        cd build
        mkdir package
        packagename="${{ runner.os }}-${{ runner.arch }}"-UZDoom-"${{ steps.ghd.outputs.describe }}"

        7z a package/licenses.zip ../docs/licenses/*

        if [[ "${{ runner.os }}" == 'Windows' ]]; then

            fetch oalsoft.zip \
                ea8bc36fd7fa05f64e13400d20886de753a227202a4ea3781913489a26b36fc6 \
                https://github.com/kcat/openal-soft/releases/download/1.23.1/openal-soft-1.23.1-bin.zip
            unzip -j oalsoft.zip openal-soft-1.23.1-bin/bin/Win64/soft_oal.dll -d package

            fetch sndfile.zip \
                2173935c0c1ed13cf627951d34483f9d405ead2eb473190461c42ba220643a3f \
                https://github.com/libsndfile/libsndfile/releases/download/1.2.2/libsndfile-1.2.2-win64.zip
            unzip -j sndfile.zip libsndfile-1.2.2-win64/bin/sndfile.dll -d package

            mkdir package/soundfonts
            cp ../soundfont/uzdoom.sf2 package/soundfonts

            mkdir package/fm_banks
            cp ../fm_banks/GENMIDI.GS.wopl ../fm_banks/gs-by-papiezak-and-sneakernets.wopn package/fm_banks

            if [[ -d ${{ inputs.build_type }} ]]; then
                mv ${{ inputs.build_type }}/* .
            fi

            cp uzdoom.* *.pk3 package

            cd package
            7z a -sdel -r "${packagename}.zip" *
            cd ..

        elif [[ "${{ runner.os }}" == 'macOS' ]]; then

            if [[ ! -d uzdoom.app ]] && [[ -d ${{ inputs.build_type }}/uzdoom.app ]]; then
                mv ${{ inputs.build_type }}/uzdoom.app uzdoom.app
            fi
            mv package/licenses.zip uzdoom.app/Contents/Resources
            cp *.pk3 uzdoom.app/Contents/MacOS

            if dsymutil uzdoom.app/Contents/MacOS/uzdoom; then
              mv uzdoom.app/Contents/MacOS/uzdoom.dSYM uzdoom.app/Contents/Resources/
            fi

            SIGN_ID="-"
            SIGN_OPTS=""

            if [[ -n "${{ secrets.MACOS_CERTIFICATE }}" ]]; then
                echo "${{ secrets.MACOS_CERTIFICATE }}" | base64 --decode > certificate.p12
                security create-keychain -p "" build.keychain
                security default-keychain -s build.keychain
                security unlock-keychain -p "" build.keychain
                security import certificate.p12 -k build.keychain -P "${{ secrets.MACOS_CERTIFICATE_PASSWORD }}" -T /usr/bin/codesign
                security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain

                SIGN_ID="${{ secrets.MACOS_CERTIFICATE_ID }}"
                SIGN_OPTS="--options=runtime"
            fi

            dylibbundler -ns -of -cd -b \
              -x ./uzdoom.app/Contents/MacOS/uzdoom \
              -d ./uzdoom.app/Contents/Libs \
              -p @executable_path/../Libs/

            xattr -cr uzdoom.app

            find uzdoom.app/Contents/Libs -type f -name "*.dylib" -print0 | while IFS= read -r -d '' file; do
                codesign --remove-signature "$file"
                codesign --force $SIGN_OPTS -s "$SIGN_ID" "$file"
            done

            /usr/bin/codesign --force --deep $SIGN_OPTS -s "$SIGN_ID" uzdoom.app -v

            cp -r uzdoom.app package

            cd package
            7z a -sdel -r "${packagename}.zip" *
            cd ..

        elif [[ "${{ runner.os }}" == 'Linux' ]]; then

            ldd ./uzdoom

            mkdir AppDir
            cmake --install . --prefix "$(realpath AppDir)/usr"

            sudo apt-get install libfuse2 # renamed to libfuse2t64 in later releases

            fetch appimage-builder \
                4b4f99cae9291d78ba12dbdabca7c0a67c72aa61eb2e5d424089171a9485e96f \
                https://github.com/AppImageCrafters/appimage-builder/releases/download/v1.1.0/appimage-builder-1.1.0-x86_64.AppImage
            chmod +x appimage-builder

            export GIT_DESCRIBE="${{ steps.ghd.outputs.describe }}"
            ./appimage-builder --skip-tests --recipe ../tools/AppImageBuilder.yml
            mv *.AppImage "package/${packagename}.AppImage"

            rm package/licenses.zip

        fi

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        path: build/package
        name: ${{ inputs.name }} ${{ inputs.build_type }}

    - name: List
      if: always()
      shell: bash
      run: |
        git status
        tree -pu build
